[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "ml"
version = "0.1.0"
dependencies = [
    "jupyter",
    "ipykernel",
    "numpy",
    "pandas",
    "matplotlib",
    "scikit-learn",
] 